#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# gnome-keyring-daemon
if [ -n "$DESKTOP_SESSION" ];then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

# elixir
export PATH="$HOME/bin/elixir/bin:$PATH"

# cabal - haskell
export PATH="$HOME/.cabal/bin/:$PATH"

# go
export GOPATH=$HOME/go:/usr/share/gocode
export PATH="${GOPATH//://bin:}/bin:$PATH"

# rash - https://github.com/tkf/rash
# alias rash="$HOME/.pyenv/versions/2.7.10/bin/rash"
# eval "$(rash init)"

# env
# export EDITOR="emacs -nw"
# export VISUAL="emacs -nw"
export EDITOR="nvim"
export VISUAL="nvim"

# set cowsay to owl as default
alias cowsay='cowsay -f owl'
export ANSIBLE_COW_SELECTION='owl'

# xmonad and java windows dialog and dropdown menu issue
export _JAVA_AWT_WM_NONREPARENTING=1

# Trellowarrior
export TRELLO_API_KEY="bb4f5aaf024d89dba8619a119aa5d7ec"
export TRELLO_API_SECRET="d5339bd538a31f412843c0a0aa8df871a7eb7c8fe4502471c00488e10b21aae0"
export TRELLO_NAME="TrelloWarrior"
export TRELLO_EXPIRATION="30days"

# android
export PATH="$HOME/android-sdk/tools/bin:$PATH"
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G"
